Handle $DEFAULT_URLS a bit more safely

diff --git a/make-eawpatches-package b/make-eawpatches-package
--- a/make-eawpatches-package
+++ b/make-eawpatches-package
@@ -301,6 +301,19 @@ process_urls() {
 	return 1
 }
 
+process_default_urls() {
+	echo "$DEFAULT_URLS" | grep -E -v '^\s*#' | shuf | {
+			# Keep in mind that the pipe created a subshell
+			while read URL; do
+				process_urls "$WORK_DIR" "$URL" && exit
+			done
+			exit 1
+		} && return 0
+
+	echo "Could not find any suitable URL" >&2
+	return 1
+}
+
 main() {
 	parse_args "$@"
 	[ "$OPT_FORCE" != true ] && verify_sanity
@@ -314,10 +327,7 @@ main() {
 	elif [ "$OPT_URL" ]; then
 		process_urls "$WORK_DIR" "$OPT_URL"
 	else
-		if ! process_urls "$WORK_DIR" $(echo "$DEFAULT_URLS" | grep -E -v '^\s*#' | shuf); then
-			echo "Could not find any suitable URL" >&2
-			exit 1
-		fi
+		process_default_urls "$WORK_DIR"
 	fi
 
 	fakeroot dpkg-deb --build "$WORK_DIR/build" .
